services:
  frontend:
    build: ./frontend
    ports: # host:container
      - "5180:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src/:/app/src # synchroniser dossier frontend/src avec app/src (défini dans Dockerfile du frontend)

  backend:
    build: ./backend 
    ports: # host:container
      - "4200:4200"  # Apollo Server GraphQL
    depends_on:
      - database
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    volumes:
      # - ./backend/data:/app/data
      - ./backend/src/:/app/src # synchroniser dossier backend/src avec app/src (défini dans Dockerfile du backend)
  
  database: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      ports:
        - "5050:80" 
      environment:
        PGADMIN_DEFAULT_EMAIL: wilder@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      depends_on:
        - database


